image: docker:latest
services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH

before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

stage:
    - build

build:
    stage: build
    script:
        - docker pull $CONTAINER_IMAGE:latest || true
        - VERSION=`git describe --tags --always --dirty --match=v* 2> /dev/null || echo test` 
        - BUILD_DATE=`date +%FT%T%z`
        - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_BUILD_REF --tag $CONTAINER_IMAGE:latest --build-arg VERSION=${VERSION} --build-arg BUILD_PKG=${CI_PROJECT_NAME} --build-arg BUILD_PORT=1323 --build-arg BUILD_ENV=.env.stage.json .
        - docker push $CONTAINER_IMAGE:$CI_BUILD_REF
        - docker push $CONTAINER_IMAGE:latest
