version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - pip install awscli --upgrade --user
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=${repository_url}/${repository_name}
      - echo Exit the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date` for $REPOSITORY_URI
      - make vendor-update
      - make swagger build
      - docker pull $REPOSITORY_URI:latest || true
      - docker build --cache-from $REPOSITORY_URI:latest --build-arg BUILD_PORT=${build_port} -t $REPOSITORY_URI:latest .
      - docker push $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $repository_name $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
